name: Build Application (main)
on:
  push:
    branches: [main]

jobs:
  build-application:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t projfordocker:${{ github.sha }} .

